name: Workflow

on: push

jobs:
  first-job:
    name: abdullah 
    runs-on: ubuntu-18.04
    steps:
    - name: flake8
      run: flake8 scrape_google.py--count--statistics--max-line-length 300
    - name: mypy
      uses: flake8 scrape_google.py--show-error-codes--disable-error-code import
    - name: isort
      uses: flake8 scrape_google.py-c--line-length 300
      with: scrape_google.py

        